### ISSUE TITLE
Header positions do not immediately update while scrolling

### ISSUE THREAD

**Issue by scuzzar** [don-tnowe/godot-resources-as-sheets-plugin#13]
In Godot 4.0 Beta 10, Table header get async to Table in the example due to scrolling horizonally

**Comment by don-tnowe** [comment]
Hello!

As long as I've been testing, a workaround is just clicking inside the table, or scrolling once with a scroll wheel. Header positions update on a mouse button event

Since I've left that in, I think I found a way to fix that, just didn't consider it high enough priority. It might be fixable, though!
