### ISSUE TITLE
Deselection of cell, if non-resource file in folder

### ISSUE THREAD

**Issue by scuzzar** [don-tnowe/godot-resources-as-sheets-plugin#15]
On Godot 4.0:

If there is any other file in the folder of the resources, edition a text or numer cell will result in deselection of the cell. This makes editing very tedius.

Works in the example project

Workaround is obviusly: not to put other files in in the resource/data folder.

By the way: i Realy like the tool :-)

**Comment by hilfazer** [comment]
I still experience this behaviour if there's a .png, .bmp or .wav file in the same folder.

**Comment by don-tnowe** [comment]
Probably also happens when a scene or script in inside, or any `.tres`/`.res` without a script (*theme, style, atlas etc.*)

I'm not sure of the use case of putting lots of custom data files (*which the tool is supposed to deal with*) along with other files, rather than in two separate folders. But still reopening, I might work on it -eventually-.

**Comment by don-tnowe** [comment]
Should be fixed, but if there are multiple types of **custom** resources, there's still #24. If anyone here has ideas on the implementation, feel free to leave a comment!
