### ISSUE TITLE
"Unusable" fields

### ISSUE THREAD

**Issue by Frontrider** [don-tnowe/godot-resources-as-sheets-plugin#3]
There are 2 fields shown that I'm gonna try to reason out of the addon:

- resource_local_to_scene : This will always be false, as no resources in the folder will ever be local to a scene, as they can not only exist inside a scene. This should not be shown.
- resource_name : I see where it is coming from, but 99% of the time I don't touch it, it's an empty field taking up space. I could try to use it, but it would just be more cumbersome to use and more difficult to refactor than it needs to be. At best, let me turn this off.

**Comment by don-tnowe** [comment]
I don't see how these would be much a bother - they are all the way to the left, so with lots of properties they won't even be visible! And they are **not** useless:

**resource_local_to_scene** is used if a resource can be modified at runtime. Most workflows avoid this, but it doesn't hurt to have. Again, it's way to the left, just scroll away.

**resource_name** is used by me **all the time** because it makes thing show up with a proper name instead of just "Resource", so editing scenes is much, much easier.

Hiding specific columns (*any of them*) is a planned feature, but implementation might take some time and I have a lot of work now.

**Comment by Frontrider** [comment]
I guess 2 more "obscure" godot features.

**Comment by don-tnowe** [comment]
Just added hiding any columns via the "||" and "Show/Hide Columns (Eye icon)" buttons, so closing this as solved!

**Comment by Frontrider** [comment]
Yes, this is amazing, thank you!
