### ISSUE TITLE
Add calculated columns

### ISSUE THREAD

**Issue by feois** [don-tnowe/godot-resources-as-sheets-plugin#46]
First of all, this plugin is cool af, thanks for making my life easier.

I'm proposing a calculated column feature that produces an output based on other properties. IDK how this plugin is implemented but I figure it might be possible using `Expression`.

For example, I currently use resources for weapons so I would like to have a DPS column that calculates using damage and cooldown so I could manage stats balancing better.

**Comment by don-tnowe** [comment]
Actually great idea. I had problems with editing sub-resources, so setting-getting with any expression would allow both derivative values and editing subresources in the table.

**Comment by Sch1nken** [comment]
I just stumbled upon the same idea. I already have functions on my resources (like get_dps() -> float). I looked around and I think it could be doable to call `get_method_list()` in addition to `get_property_list()` (and save them to a separate dictionary). 

I was hoping to use custom annotations, but these are not a thing (yet). So my broad approach would be:
Is it an internal function? -> don't use
Does the function take arguments? -> don't use
Is the function static? -> don't use

All other functions should be fine. Instead of filling the raw value of a property, the script would then call func_name.call() and save the returned value.

I'm currently working on another project (just had a look at this amazing addon for a future (currently on hold) project). I can take a look at it in a few weeks hopefully (and provide a pull request).

**Comment by don-tnowe** [comment]
This can already be done using `@export` properties with a getter - they behave like any other property, so will show up in the table:

    @export var weapon_damage := 0.0
    @export var weapon_cooldown := 0.0
    @export var weapon_dps := 0.0:
        set(v):
            weapon_damage = v * weapon_cooldown
        get:
            return weapon_damage / weapon_cooldown if weapon_cooldown != 0.0 else 0.0

However, it comes with limitations:

- must be a `@tool` script, but you'll already have this on since it's safe for `Resource`s and needed for setters/getters;
- the table cell must be updated when another property changes, and currently it isn't.

Cells could be set to update automatically when any other property changes, possibly uniquely to `@tool` scripts and to properties with `set`/`get` (*but not sure how to do that*), so this feature should be easy to take care of without adding an additional system with manual configuration.

> not sure if you can reference non-static callables in a static context

You can't, but methods can be accessed via its `StringName` name, if an object with the method is provided. Same with properties, which is how this plugin works.

**Comment by don-tnowe** [comment]
Well, that was easy. 7 lines changed: 2aa282bdd5c45b08cb850bc30c0b5d5f062800a5
