### ISSUE TITLE
High page count causes editor view to expand beyond viewport bounds (+fix)

### ISSUE THREAD

**Issue by cedahl** [don-tnowe/godot-resources-as-sheets-plugin#63]
In 4.0 the page count container gets really wide and isn't bound by a parent, causing controls on the right side of the screen to potentially become inaccessible. This can be seen by setting the Rows Per Page count to 2 and opening the Random Upgrades example folder.

![image](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/129879543/62a00d43-de8e-4d99-86b0-d5f0deb61ab2)

I needed to fix this for my project which has an obscene number of resources, so let me know if you want the modified `editor_view.tscn` and `table_pages.gd` or if I can PR it or something. Here's the result, with a scroll added to the page buttons:

![image](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/129879543/398389d9-791a-4cbd-954c-3a88eb4808cb)

**Comment by don-tnowe** [comment]
Oh, I never got that problem! Good fix, a scroll container is a pretty compact solution.

It does leave some extra margins though, because space must be made for the scrollbar. Doesn't quite look as neatly packed anymore:

![image](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/assets/67479453/9a9de059-6ba3-4dbd-bee9-6c98c093220c)
