### ISSUE TITLE
Feature request: import/export to CSV

### ISSUE THREAD

**Issue by Zireael07** [don-tnowe/godot-resources-as-sheets-plugin#9]
I have an existing table of stuff in CSV format. Moving it to resources, while fragmenting the data into multiple .tres files, would make parsing the data much easier...

**Comment by don-tnowe** [comment]
Sound good! Converting to/from resources should be no problem.

The plugin was originally made to help projects that already use resources - If what you have is already a table, perhaps it should be worth expanding the plugin to access them directly? I'm already thinking of ways to refactor for that.

**Comment by Zireael07** [comment]
Parsing CSV in Godot 3.5 is a PITA currently (I have to do data[0] instead of data["name"], which becomes really nasty the more columns I have). If the extension could handle that transparently, akin to how Resources do that, then yes, expanding to access CSV directly is also an option.

**Comment by don-tnowe** [comment]
Hmm. Sounds like your problem is easier to be solved by just creating an `enum` with all column names - column inserted, enum entry added.

Though I'm still working on csv -> resource import. Will notify here either way once I finish.

**Comment by don-tnowe** [comment]
Alright, should be up on `master`! Import button is on the top bar. 

Worth testing if the Color (from hex like `#ff01c5`), Bool (from some commonly used binary-classification words) and Resource (from `"res://"` paths) types get imported properly. Enums already work, but worth testing on other datasets.

**Comment by don-tnowe** [comment]
Hope you didn't get too deep into that pile o' resources, because a way to ACTUALLY EDIT CSV FILES should now be up as well.

Known issues:
- **can't import a file more than once, property list won't change** - to fix, delete the generated script and .tres in the .csv's folder
- **there can be a 5 sec delay before the CSV actually gets saved,** so please don't go wild with refreshing the table after editing values. This was added to improve performance (csv can be huge, don't save 10x a second), but in retrospect the delay is too high. Delay can be tweaked in `import_export/formats_edit/edit_csv.gd:36`.

**Comment by Zireael07** [comment]
Doesn't seem to work in 3.5 - lots of errors in the output, mostly that replace() is called on nil.

This is regardless of me setting the column types to something or leaving them as String

**Comment by don-tnowe** [comment]
Missing values? Rows don't have the same number of values? Enum properties named like built-in types? Space after commas breaks reading?

Should be fixed now. Let's see if I missed something else.

**Comment by Zireael07** [comment]
I think it was missing values/rows not having same number of values, I'll take a look later :)

**Comment by Zireael07** [comment]
Seems to work, but I'll double check with that earlier CSV with unequal rows ;)
